### ISSUE TITLE
[Feedback Bar] Submit a bug ticket to GitHub

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-beta-tester#15]
This link (in the admin bar) should pre-populate information on the GitHub side.

- System status report
- Version (in issue title)
- Issue template

We should add caching the status report so it's not regenerated on all screens.

**Comment by bor0** [comment]
@kloon and I briefly discussed about the potential solution for this.

If we decide to use the Github API for opening issues, we'll probably need tokens/auth for that.

We could go down that road, or simply redirect to https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md (we can also pre-populate title by appending `&title=test` and body by appending `&body=woot%26woot`)

However, `System status report` might be a bit tricky for a query string, since it seems that we cannot `POST` to `issues/new`.

**Comment by mikejolley** [comment]
@bor0 Could we summarize the system status and try to send what we can via query string (as much as allowed?)

**Comment by bor0** [comment]
Also by sending `body` we will be overriding the template, e.g. see:
https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md&body=test

Not sure what the best approach is in this case

**Comment by kloon** [comment]
How about reading the template file via a remote request and then replacing the values in there before passing it through as the body?

**Comment by bor0** [comment]
We can use something like:
```
$response = wp_remote_get( 'https://raw.githubusercontent.com/woocommerce/woocommerce/master/.github/ISSUE_TEMPLATE/Bug_report.md' );

// Get SSR
// TODO: See what we can re-use from core `includes/admin/views/html-admin-page-status-report.php`
ob_start();
WC_Admin_Status::status_report();
$ssr = ob_get_clean();

$body = str_replace( 'Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.', $ssr, $response['body'] );
```

But I don't know if there's a neater way to get the status report, as `WC_Admin_Status::status_report()` returns the whole html while we only need the smaller part in the textarea.
