### ISSUE TITLE
[GlobalStep - WooCommerce 4.7 Beta 1][Mac] "Close" button on Switch version pop up appears misaligned. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-beta-tester#77]
## Bug Description:
"Close" button on Switch version pop up appears misaligned.

## Environment:
High Sierra: 10.14.6 (18G103)
Browser: Chrome (v85.0.4183.83)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta Tester.
1. Select any version and click on "Switch version" button.  
1. Note that Switch version pop up appears.
1. Observe that "Close" button appears misaligned.
 
## Actual Result:
"Close" button on Switch version pop up appears misaligned.

## Expected Result:
"Close" button on Switch version pop up should be displayed properly aligned.

## Artifacts:
![#28061](https://user-images.githubusercontent.com/41110392/96897193-fa864a00-14ab-11eb-8f08-f703d5a01a4b.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Noting that this issue had been reported previously here https://github.com/woocommerce/woocommerce-beta-tester/issues/61. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

It was also fixed in https://github.com/woocommerce/woocommerce-beta-tester/pull/71 - we should be releasing a new version of the Beta Tester Plugin soon.
